# Generated by Django 5.0.6 on 2024-05-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeworkuser',
            name='time_work',
            field=models.CharField(default='1', editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
