# Generated by Django 5.0.6 on 2024-05-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexports',
            name='user',
        ),
        migrations.DeleteModel(
            name='TimeWorkUser',
        ),
        migrations.DeleteModel(
            name='UserExports',
        ),
    ]
