# Generated by Django 5.0.6 on 2024-05-23 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_remove_userexports_user_delete_timeworkuser_and_more'),
        ('custom_user', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexports',
            options={'verbose_name': 'برداشت کاربر', 'verbose_name_plural': 'برداشت های کاربران'},
        ),
        migrations.CreateModel(
            name='UserWorksHourRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.user', verbose_name='کارمند')),
            ],
        ),
    ]
