# Generated by Django 5.0.6 on 2024-05-23 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_remove_userexports_user_delete_timeworkuser_and_more'),
        ('custom_user', '0008_remove_userworkshourrequests_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkshourrequests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='custom_auth.user', unique=True, verbose_name='کارمند'),
        ),
    ]
