# Generated by Django 5.0.6 on 2024-05-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(db_index=True, max_length=80, primary_key=True, serialize=False, unique=True, verbose_name='نام کاربری')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی کارمند')),
                ('price', models.IntegerField(db_index=True, verbose_name='درآمد به ازای هر ساعت')),
                ('active', models.BooleanField(default=False, verbose_name='فعال یا غیر فعال')),
                ('password', models.CharField(max_length=100, verbose_name='رمز عبور')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین است یا خیر')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
    ]
