# Generated by Django 5.0.6 on 2024-05-21 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeWorkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200, verbose_name='روز کاری')),
                ('start_time', models.CharField(max_length=200, verbose_name='ساعت شروع')),
                ('end_time', models.CharField(blank=True, max_length=200, null=True, verbose_name='ساعت پایان')),
                ('time_work', models.CharField(editable=False, max_length=50, verbose_name='مقدار ساعت کار کارمند در این روز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.user', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'ساعات کار کاربر',
                'verbose_name_plural': 'ساعات کار کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserExports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_count', models.IntegerField(verbose_name='مقدار برداشتی به تومان')),
                ('date', models.CharField(max_length=200, verbose_name='تاریخ برداشت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ( اختیاری )')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.user', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'برداشت کاربر',
                'verbose_name_plural': 'برداشت کاربران',
            },
        ),
    ]
