# Generated by Django 5.0.6 on 2024-05-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='درآمد')),
                ('day', models.CharField(max_length=100, verbose_name='روز')),
            ],
            options={
                'verbose_name': 'درآمد در روز',
                'verbose_name_plural': 'درآمد های روزانه',
            },
        ),
        migrations.CreateModel(
            name='PriceExportDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100, verbose_name='روز')),
                ('price', models.IntegerField(verbose_name='هزینه')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'هزینه در روز',
                'verbose_name_plural': 'هزینه های روزانه',
            },
        ),
    ]
