# Generated by Django 5.0.6 on 2024-05-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceday',
            name='price',
            field=models.IntegerField(verbose_name='درآمد'),
        ),
    ]
